format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_metrics\
$line_break\
$character"""

[username]
disabled = false

[gcloud]
disabled = true
