#!/usr/bin/env bash

zenity --question \
    --title "" \
    --text "<big>Do you really want to shut down?</big>" \
    --icon "application-exit-symbolic" \
    --timeout 0 \
    --default-cancel

if [ $? -eq 0 ]; then
    systemctl poweroff
fi
