#!/usr/bin/env bash

queries=("cyberpunk" "futuristic city at night")
query=${queries[ $RANDOM % ${#queries[@]} ]}
access_key=$(<~/.scripts/.unsplash-key)
wget -q -O- "https://api.unsplash.com/photos/random/?query=${query}" --header="Authorization: Client-ID ${access_key}" \
    | jq -r '.urls.full' \
    | wget -q -i- -O ~/.scripts/bg.jpg
hyprctl hyprpaper reload ,"~/.scripts/bg.jpg"
