#!/usr/bin/env bash

# old
# wget -q https://picsum.photos/1920/1080 -O ~/.scripts/bg.jpg

# queries=("castle" "city,night" "lake" "forest" "ruin" "landscape" "nature")
queries=("autumn castle" "autumn nature", "autumn landscape", "autumn forest", "autumn lake", "fall castle" "fall nature", "fall landscape", "fall forest", "fall lake")
query=${queries[ $RANDOM % ${#queries[@]} ]}
access_key="j4kixIcyzlzlKL0adn7PnLAGKDNqN42FVHnXy5cUo8Q"
wget -q -O- "https://api.unsplash.com/photos/random/?query=${query}" --header="Authorization: Client-ID ${access_key}" \
    | jq -r '.urls.full' \
    | wget -q -i- -O ~/.scripts/bg.jpg
feh --bg-fill ~/.scripts/bg.jpg
