#!/usr/bin/env bash

# old
# wget -q https://picsum.photos/1920/1080 -O ~/.scripts/bg.jpg

# change search term to whatever you like
wget -q https://source.unsplash.com/random/1920x1080/?landscape -O ~/.scripts/bg.jpg
feh --bg-fill ~/.scripts/bg.jpg
